### ISSUE TITLE
Channel disconnected at browser refresh.

### ISSUE THREAD

**Issue by puruzio** [saschatimme/elm-phoenix#30]
Hi, First of all, thanks for this great library.

My project is based on the Elm example here (https://github.com/saschatimme/elm-phoenix/blob/master/example/assets/elm/src/Chat.elm) and it's working well except the phoenix channel seems to be disconnected whenever the browser is refreshed, which then causes the connection to be removed from the Phoenix Presence list.

I understand elm-phoenix reconnects automatically as long as the channel to join is specified in the channel list as in `connect socket [channel]`. But where in the example code, does it handle reconnecting the channel (e.g., by setting isActive to True such that the subscription puts `lobby` back in the channel list), or is it something I should handle via localstorage, etc? 

Thanks in advance.

**Comment by saschatimme** [comment]
Sorry for the late answer. The problem here is that a refresh of the browser purges all existing JavaScript code and executes everything from fresh (as it obviously should be). Thus, you have to use LocalStorage / SessionStorage to manually serialize / deserialize your state. This is nothing what this library can handle.
